language: python
python:
  - "3.5"
services:
  - mysql
env:
  - DJANGO=1.8 DB=mysql
before_install:
  - sudo apt update
  - sudo apt install qemu-kvm libvirt-bin virt-manager virt-viewer virtinst
  - sudo apt install libvirt-python libvirt-dev
  - pip3 install libvirt-python
  - sudo apt-get install ansible libssl-dev
  - pip3 install ansible
  - sudo pip3 install Django
  - pip3 install docker
# before_script:
#   - mysql -e 'create database test;' -u root
script:
  - python manage.py test
