# ansible-playbook create_ns.yml 
# validate by 
#   sudo ip netns exec adminns ping 8.8.8.8
---
- hosts: localhost
  gather_facts: no
  vars: 
    target: "{{ target_proj }}"
  tasks:
    - name: create admin namespace
      command: "{{ item }}"
      with_items: 
        - ip netns add adminns
        - ip link add adminnsint1 type veth peer name adminnsint2
        - ip link set adminnsint2 netns adminns
        - ip addr add 102.1.1.1/24 dev adminnsint1
        - ip link set dev adminnsint1 up
        - ip netns exec adminns ip addr add 102.1.1.2/24 dev adminnsint2
        - ip netns exec adminns ip link set dev adminnsint2 up
        - ip netns exec adminns ip route add default via 102.1.1.1
        - iptables -t nat -A POSTROUTING  -s 102.1.1.0/24 -o enp0s3 -j MASQUERADE
      become: yes
      become_method: sudo
