# ansible-playbook create.yml --extra-vars "ctn_name=vm_test"
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: build from Dockerfile
      command: docker run -itd --name {{ ctn_name }} --network {{br_name}} myubuntu
      become: yes
      become_method: sudo 

    - name: configure port_num in namespace
      command: "{{ item }}"
      with_items: 
        - ip netns exec adminns iptables -t nat -A PREROUTING -p tcp --dport {{port_num}} -j DNAT --to-destination 1.1.3.2:{{port_num}}
        - ip netns exec {{proj_ns}} iptables -t nat -A PREROUTING -p tcp --dport {{port_num}} -j DNAT --to-destination 1.1.4.2:{{port_num}}
      become: yes
      become_method: sudo 