# sudo ansible-playbook config.yml -i hosts
# while true; do curl -m1 [IP_ADDRESS]; done
---
- hosts: LBs
  gather_facts: no
  tasks:
    - name: configure PRE-ROUTING
      command: "{{ item }}"
      with_items: 
        - sudo iptables -t nat -A PREROUTING -p tcp  -i eth1 --dport 80 -m state --state NEW -m statistic --mode nth --every 3 --packet 0 -j DNAT --to-destination 35.237.181.53
        - sudo iptables -t nat -A PREROUTING -p tcp  -i eth1 --dport 80 -m state --state NEW -m statistic --mode nth --every 3 --packet 1 -j DNAT --to-destination 35.196.112.92 
        - sudo iptables -t nat -A PREROUTING -p tcp  -i eth1 --dport 80 -m state --state NEW -m statistic --mode nth --every 3 --packet 2 -j DNAT --to-destination 35.227.124.229
      become: yes
      become_method: sudo

