# ansible-playbook create.yml --extra-vars "target_vm=vm_test"
---
- hosts: localhost
  gather_facts: no
  vars: 
    target_vm: "{{ target_vm }}"
  tasks:
    - name: copy template_vm to target_vm
      command: sudo virt-clone --original zlu24vm1 --name "{{ target_vm }}"  --auto-clone

    - name: restart target_vm
      command: virsh start "{{ target_vm }}"
      become: yes
      become_method: sudo
      