# sudo ansible-playbook config.yml -i hosts --extra-vars "ip1=1.1.4.2/24 ip2=1.1.4.1"
---
- hosts: VMs
  gather_facts: no
  tasks:
    - name: configure IP on bridge devices
      command: "{{ item }}"
      with_items:
        - sudo ip addr del {{ ip1 }} dev eth1
        - sudo ip route del default
      become: yes
      become_method: sudo