# ansible-playbook create_ns.yml --extra-vars "target_proj=proj0 ip_int1=1.1.3.2/24 ip_int2=1.1.3.1/24 source=1.1.3.0/24"
# validate by 
#   1. sudo ip netns list
#   2. sudo ip netns exec adminns ip link show
#   3. sudo ip netns exec {target_proj}ns ip link show
#   4. sudo ip netns exec {target_proj}ns ping 8.8.8.8
---
- hosts: localhost
  gather_facts: no
  vars: 
    target: "{{ target_proj }}"
  tasks:
    - name: Create a namespace named as the value of target_ns
      command: ip netns add "{{ target }}"ns
      become: yes
      become_method: sudo

    - name: create a veth pair and attach to each namespace
      # command: "sh /home/ansible/subnet/ns.sh {{target}}"
      command: "{{ item }}"
      with_items: 
        - ip link add {{target}}int1 type veth peer name {{target}}int2
        - ip link set {{target}}int1 netns {{target}}ns
        - ip link set {{target}}int2 netns adminns
        - ip netns exec {{target}}ns ip link set dev {{target}}int1 up
        - ip netns exec adminns ip link set dev {{target}}int2 up
        - ip netns exec {{target}}ns ip addr add {{ ip_int1 }} dev {{target}}int1
        - ip netns exec adminns ip addr add {{ ip_int2 }}/24 dev {{target}}int2
        - ip netns exec {{target}}ns ip route add default via {{ ip_int2 }}
        - ip netns exec adminns iptables -t nat -A POSTROUTING -s {{ source }} -o adminint2 -j MASQUERADE
      become: yes
      become_method: sudo
