# delete the bridge and delete the network
# ansible-playbook delete_net.yml --extra-vars "net_name=net_test br_name=br_test"
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: stop the network
      virt_net:
       command: destroy
       name: "{{ net_name }}"

    - name: undefine the network 
      virt_net:
       command: undefine
       name: "{{ net_name }}"

    - name: set down the bridge
      command: ip link set down "{{ br_name }}"
      become: yes
      become_method: sudo

    - name: delete the bridge
      command: brctl delbr "{{ br_name }}"
      become: yes
      become_method: sudo

    - name: detach the bridge
      command: ip link delete {{br_name}}int4
      become: yes
      become_method: sudo
