# ansible-playbook delete_ns.yml --extra-vars "target_proj=proj0"
# validate by sudo ip netns list
---
- hosts: localhost
  gather_facts: no
  vars: 
    target: "{{ target_proj }}"
  tasks:
    - name: delete interfaces
      command: "{{ item }}"
      with_items: 
        - ip netns exec {{ target }}ns ip link set dev {{target}}int1 down
        - ip netns exec adminns ip link set dev {{target}}int2 down
        - ip netns exec {{ target }}ns ip link delete {{target}}int1
      become: yes
      become_method: sudo

    - name: Delete a namespace named as the value of target_ns
      command: ip netns del "{{ target }}"ns
      become: yes
      become_method: sudo
