# define a bridge and define the network in NAT / DHCP mode
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Define the network internet in NAT / DHCP mode
      virt_net:
       command: define
       name: admin_net
       xml: '{{ lookup("template", "admin_net.xml") }}'
       state: present

    - name: Start the network Internet
      virt_net:
       state: active
       name: admin_net